# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = NodeComposer
DESTDIR = ../x64/Debug
CONFIG += debug console
LIBS += -L"." \
    -lC:/libs/lua-5.4.2/lua54
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(NodeComposer.pri)
